function createfigure(XData1, YData1, Parent1)
%CREATEFIGURE(XData1, YData1, Parent1)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  PARENT1:  text parent

%  Auto-generated by MATLAB on 15-Apr-2022 01:24:06

% Create figure
figure1 = figure('Tag','ScopePrintToFigure',...
    'Color',[0.156862745098039 0.156862745098039 0.156862745098039]);
colormap(jet);

% Create axes
axes1 = axes('Tag','VisualAxes','Parent',figure1,'Units','pixels');
hold(axes1,'on');
colororder([1 1 0.0666666666666667;0.0745098039215686 0.623529411764706 1;1 0.411764705882353 0.16078431372549;0.392156862745098 0.831372549019608 0.0745098039215686;0.717647058823529 0.274509803921569 1;0.0588235294117647 1 1;1 0.0745098039215686 0.650980392156863]);

% Create line
line(XData1,YData1,'DisplayName','Channel 1','Tag','DisplayLine1',...
    'Parent',axes1,...
    'Color',[1 1 0.0666666666666667]);

% Create ylabel
ylabel('PSD (dBm / Hz)',...
    'Color',[0.686274509803922 0.686274509803922 0.686274509803922]);

% Create xlabel
xlabel('Frequency (MHz)',...
    'Color',[0.686274509803922 0.686274509803922 0.686274509803922]);

% Create title
title('Baseband IEEE 802.11ac Waveform','Units','normalized',...
    'Color',[0.686274509803922 0.686274509803922 0.686274509803922]);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-120 120]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-151.420195171008 -34.828608208066]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[0 1]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'CLim',[-80 20],'Color',[0 0 0],'FontSize',8.5,'GridAlpha',0.3,...
    'GridColor',[0.686274509803922 0.686274509803922 0.686274509803922],'Layer',...
    'top','OuterPosition',[0 0 410 264],'XColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],'XGrid','on',...
    'YColor',[0.686274509803922 0.686274509803922 0.686274509803922],'YGrid',...
    'on','ZColor',[0.686274509803922 0.686274509803922 0.686274509803922],...
    'ZTick',[0 0.5 1]);
% Create text
text('Tag','StatusBarReadoutText','Parent',Parent1,'Units','pixels',...
    'VerticalAlignment','bottom',...
    'String','RBW=100 kHz, Sample rate=240 MHz',...
    'Position',[0 0 0],...
    'Color',[0.686274509803922 0.686274509803922 0.686274509803922],...
    'Visible','on');

